CREATE DATABASE[Ambulance]
GO
USE [Ambulance]
GO
CREATE TABLE[Person](
[ID] INT PRIMARY KEY IDENTITY,
[FirstName] NVARCHAR(50) NOT NULL,
[LastName] NVARCHAR(50) NOT NULL,
[MiddleName] NVARCHAR(50),
[CharacterID] INT FOREIGN KEY REFERENCES [Role](ID) NOT NULL,
[AmbulanceTeamID] INT FOREIGN KEY REFERENCES [AmbulanceTeam](ID),
[Birthday] DATE NOT NULL,
[PhoneNumber] INT NOT NULL

);
GO
CREATE TABLE[Role](
[ID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL
);
GO
CREATE TABLE [AmbulanceTeam](
[ID] INT PRIMARY KEY IDENTITY,
[CarBrandID] INT FOREIGN KEY REFERENCES [CarBrand](ID),
[CarNumber] NVARCHAR(10) NOT NULL
);
GO
CREATE TABLE[CarBrand](
[ID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL
);
GO
CREATE TABLE[InvokeTeam](
[ID] INT PRIMARY KEY IDENTITY,
[PatientID] INT FOREIGN KEY REFERENCES [Person](ID) NOT NULL,
[AmbulanceTeamID] INT FOREIGN KEY REFERENCES [AmbulanceTeam](ID) NOT NULL,
[Date] DATETIME NOT NULL
);